services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car_chat_dashboard
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - car_chat_network

networks:
  car_chat_network:
    driver: bridge
